// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:cupertino_native/channel/params.dart';
import 'package:cupertino_native/components/cn_widget.dart';
import 'package:cupertino_native/components/cn_widget_state.dart';
import 'package:cupertino_native/cupertino_native.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

const _kNativeViewType = 'CupertinoNativeSearchField2';

/// Callback invoked when the native search field needs suggestions.
///
/// Return the sections to display, in order. Return an empty list to show no
/// suggestions at all.
typedef CNSearchSuggestionsCallback =
    FutureOr<List<CNSuggestionSection>> Function(String query);

/// A single entry of the native suggestions popup, mapping to
/// `NSSuggestionItem`.
@immutable
class CNSuggestionItem {
  /// Creates a suggestion item.
  const CNSuggestionItem({
    required this.title,
    this.secondaryTitle,
    this.value,
    this.systemImage,
    this.imageColor,
    this.help,
  });

  /// Optional tooltip shown when hovering the item.
  final String? help;

  /// Optional color applied to [systemImage] as an SF Symbol palette color.
  ///
  /// When null the symbol is rendered with the popup's default treatment.
  final Color? imageColor;

  /// Secondary (subtitle) line displayed below [title].
  final String? secondaryTitle;

  /// Optional SF Symbol name shown as the item's leading image.
  final String? systemImage;

  /// The primary line of text displayed for the item.
  final String title;

  /// Text written into the search field when the item is picked.
  ///
  /// Defaults to [title] when null.
  final String? value;

  /// The text this item inserts into the field once selected.
  String get effectiveValue => value ?? title;

  /// Serializes the item for the native side. [id] is generated by
  /// [CNSearchField] and echoed back when the item is selected.
  Map<String, dynamic> toMap(BuildContext context, {required String id}) {
    return <String, dynamic>{
      'id': id,
      'title': title,
      'secondaryTitle': secondaryTitle,
      'value': effectiveValue,
      'systemImage': systemImage,
      'imageColor': resolveColorToArgb(imageColor, context),
      'help': help,
    };
  }
}

/// A group of [CNSuggestionItem]s displayed under an optional header, mapping to
/// `NSSuggestionItemSection`.
@immutable
class CNSuggestionSection {
  /// Creates a section of suggestion items.
  const CNSuggestionSection({required this.items, this.title});

  /// Convenience constructor building a section out of plain strings.
  CNSuggestionSection.strings(List<String> values, {this.title})
    : items = List<CNSuggestionItem>.unmodifiable(
        values.map((value) => CNSuggestionItem(title: value)),
      );

  /// The items shown in this section.
  final List<CNSuggestionItem> items;

  /// Optional section header. When null the section renders without a title.
  final String? title;
}

/// A native macOS search field backed by NSSearchField.
///
/// The text is driven by a [TextEditingController], exactly like [CNTextField]:
/// programmatic changes to the controller are pushed to the native field, and
/// user edits are written back into the controller.
///
/// Suggestions are provided via [onSuggestionsRequested]. When the user types,
/// native code calls this callback and displays the returned sections (each item
/// supports a title, a secondary title and an SF Symbol image). If null, no
/// suggestions are shown.
class CNSearchField extends CNWidget {
  const CNSearchField({
    super.key,
    super.debugLog,
    this.controller,
    this.placeholder,
    this.textColor,
    this.placeholderColor,
    this.font,
    this.controlSize = CNControlSize.regular,
    this.bezelStyle = CNTextFieldBezelStyle.round,
    this.autofocus = false,
    this.enabled = true,
    this.onChanged,
    this.onSubmitted,
    this.onFocusChange,
    this.onSuggestionsRequested,
    this.onSuggestionSelected,
    this.shrink = true,
    this.constraints,
    this.tint,
    this.foregroundColor,
    this.paddings,
    this.help,
  });

  /// Whether the field should automatically receive focus when created.
  final bool autofocus;

  /// The border/bezel style of the search field.
  final CNTextFieldBezelStyle bezelStyle;

  /// The text editing controller that controls the search text.
  /// If null, an internal controller is created.
  final TextEditingController? controller;

  /// The size of the native AppKit control.
  final CNControlSize controlSize;

  /// Whether the native control accepts user interaction.
  final bool enabled;

  /// Optional native NSFont descriptor.
  final CNFont? font;

  /// Called when the field gains (`true`) or loses (`false`) focus.
  final ValueChanged<bool>? onFocusChange;

  /// Called whenever the user changes the search text.
  final ValueChanged<String>? onChanged;

  /// Called when the user submits the search text (presses Enter or selects a suggestion).
  final ValueChanged<String>? onSubmitted;

  /// Called with the item the user picked from the suggestions popup.
  ///
  /// Fires before [onSubmitted]. The item is the very instance returned by
  /// [onSuggestionsRequested], so any extra data can be looked up from it.
  final ValueChanged<CNSuggestionItem>? onSuggestionSelected;

  /// Callback used to provide suggestions while the user types.
  /// Return an empty list to show no suggestions.
  /// If null, suggestions are disabled entirely.
  final CNSearchSuggestionsCallback? onSuggestionsRequested;

  /// Placeholder string shown when the field is empty.
  final String? placeholder;

  /// The placeholder color of the search field.
  final Color? placeholderColor;

  /// The text color of the search field.
  final Color? textColor;

  @override
  final BoxConstraints? constraints;

  @override
  final Color? foregroundColor;

  @override
  final String? help;

  @override
  final EdgeInsetsGeometry? paddings;

  @override
  final bool shrink;

  @override
  final Object? tint;

  @override
  State<CNSearchField> createState() => _CNSearchFieldState();

  @override
  String get nativeViewType => _kNativeViewType;
}

class _CNSearchFieldState extends CNWidgetState<CNSearchField> {
  TextEditingController? _internalController;

  /// Items of the batch currently displayed by the native popup, keyed by the
  /// id handed to native. Lets `suggestionSelected` resolve back to the exact
  /// [CNSuggestionItem] the app returned.
  Map<String, CNSuggestionItem> _visibleSuggestions = const {};
  int _suggestionGeneration = 0;

  @override
  Size computeDefaultSize() => const Size(double.infinity, 24.0);

  @override
  void initState() {
    super.initState();
    if (widget.controller == null) {
      _internalController = TextEditingController();
    }
    _controller.addListener(_onControllerChanged);
  }

  @override
  void didUpdateWidget(covariant CNSearchField oldWidget) {
    if (oldWidget.controller != widget.controller) {
      final oldController = oldWidget.controller ?? _internalController!;
      oldController.removeListener(_onControllerChanged);

      if (widget.controller == null) {
        _internalController ??= TextEditingController(text: oldController.text);
      } else {
        _internalController?.dispose();
        _internalController = null;
      }

      _controller.addListener(_onControllerChanged);
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  void dispose() {
    _controller.removeListener(_onControllerChanged);
    _internalController?.dispose();
    _internalController = null;
    super.dispose();
  }

  @override
  Set<Factory<OneSequenceGestureRecognizer>>? get gestureRecognizers => {
    Factory<OneSequenceGestureRecognizer>(() => TapGestureRecognizer()),
  };

  @override
  Future<dynamic> onNativeMethodCall(MethodCall call) async {
    switch (call.method) {
      case 'textChanged':
        final text = call.arguments as String? ?? '';
        logDebug('textChanged: "$text"');
        _setTextFromNative(text);
        widget.onChanged?.call(text);
      case 'submitted':
        final text = call.arguments as String? ?? _controller.text;
        logDebug('submitted: "$text"');
        widget.onSubmitted?.call(text);
      case 'focusChanged':
        final focused = call.arguments as bool? ?? false;
        logDebug('focusChanged: $focused');
        widget.onFocusChange?.call(focused);
      case 'suggestionSelected':
        final args = call.arguments as Map?;
        final id = args?['id'] as String?;
        final value = args?['value'] as String? ?? '';
        logDebug('suggestionSelected: id=$id value="$value"');
        _setTextFromNative(value);
        widget.onChanged?.call(value);
        final item = id == null ? null : _visibleSuggestions[id];
        if (item != null) {
          widget.onSuggestionSelected?.call(item);
        }
        widget.onSubmitted?.call(value);
      case 'requestSuggestions':
        final args = call.arguments as Map?;
        final query = (args?['query'] as String?) ?? '';
        logDebug('requestSuggestions: query="$query"');
        final provider = widget.onSuggestionsRequested;
        if (provider == null) return _encodeSections(const []);
        final sections = await provider(query);
        logDebug('requestSuggestions: returning ${sections.length} section(s)');
        return _encodeSections(sections);
    }
    return null;
  }

  @override
  Map<String, dynamic> toWidgetPayload(
    BuildContext context, {
    required BoxConstraints? constraints,
  }) {
    final payload = <String, dynamic>{
      'text': _controller.text,
      'placeholder': widget.placeholder,
      'textColor': resolveColorToArgb(widget.textColor, context),
      'placeholderColor': resolveColorToArgb(widget.placeholderColor, context),
      'font': widget.font?.toMap(),
      'controlSize': widget.controlSize.name,
      'bezelStyle': widget.bezelStyle.name,
      'autofocus': widget.autofocus,
      'enabled': widget.enabled,
      'hasSuggestions': widget.onSuggestionsRequested != null,
    };

    widget.writeSharedFields(
      context,
      payload: payload,
      constraints: constraints,
    );
    return payload;
  }

  TextEditingController get _controller =>
      widget.controller ?? _internalController!;

  /// Serializes [sections] for native, assigning each item an id unique to this
  /// batch so the selection callback can resolve it back.
  Map<String, dynamic> _encodeSections(List<CNSuggestionSection> sections) {
    final generation = ++_suggestionGeneration;
    final lookup = <String, CNSuggestionItem>{};
    final encoded = <Map<String, dynamic>>[];

    for (var s = 0; s < sections.length; s++) {
      final section = sections[s];
      final items = <Map<String, dynamic>>[];
      for (var i = 0; i < section.items.length; i++) {
        final id = '$generation:$s:$i';
        lookup[id] = section.items[i];
        items.add(section.items[i].toMap(context, id: id));
      }
      encoded.add(<String, dynamic>{'title': section.title, 'items': items});
    }

    _visibleSuggestions = lookup;
    return <String, dynamic>{'sections': encoded};
  }

  void _onControllerChanged() {
    if (!mounted) return;
    logDebug('_onControllerChanged: text="${_controller.text}"');
    // Trigger a rebuild so the patch system pushes the text to native. This runs
    // for native-originated changes too: the base class only diffs against the
    // last payload it sent, so skipping the rebuild would leave `text` stale
    // there and a later programmatic reset to that stale value (e.g.
    // `controller.clear()` after the user typed) would diff to nothing and never
    // reach the native field. Echoing a value native already has is free — it
    // compares before assigning.
    setState(() {});
  }

  /// Writes native-originated text into the controller.
  void _setTextFromNative(String text) {
    if (_controller.text == text) return;
    _controller.text = text;
  }
}
